# Étape 1 : build de l’app avec Vite
FROM node:20-alpine AS builder

WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm install

COPY . .

# Build Vite : génère le dossier "dist"
RUN npm run build


# Étape 2 : serveur NGINX pour servir les fichiers
FROM nginx:1.25-alpine

RUN rm -rf /usr/share/nginx/html/*

# ⚠️ Attention ici : dist (et non build)
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
