// theme.js
const light = {
    w: '',
    bgColor: 'bg-white',
    textColor: 'text-gray-800',
    secondaryText: 'text-gray-500',
    borderColor: 'border-gray-200',
    hoverBg: 'hover:purple-600',
    headerBg: 'bg-gray-50',
    inputBg: 'bg-gray-100 text-gray-800',
    emptyStateText: 'text-gray-500',
    searchHover: 'hover:bg-gray-200',
    filterHover: 'hover:text-gray-700',
    clearAllText: 'text-red-500 hover:text-red-700',
    successText: 'text-green-600',
    missedText: 'text-red-600',
    //accentColor: 'blue-500',
    //accentBg: 'bg-blue-500',
    accentText: 'text-white',
    accentColor: 'purple-600',
    accentBg: 'bg-gradient-to-r from-purple-600 to-pink-600',
    accentShadow: 'shadow-[0_0_20px_rgba(124, 58, 237, 0.7)]',
    focusRing: 'focus:ring-blue-500',
    baccentText: 'text-blue-600',
    bfilterHover: 'hover:bg-blue-50 hover:text-blue-700',
    messageBg: 'bg-gray-50',
  };
  
  const dark = {
    w: '',
    bgColor: 'bg-gray-900',
    textColor: 'text-gray-100',
    secondaryText: 'text-gray-300',
    borderColor: 'border-gray-700',
    hoverBg: 'hover:bg-gray-700',
    headerBg: 'bg-gray-900',
    inputBg: 'bg-gray-700 text-white',
    emptyStateText: 'text-gray-400',
    searchHover: 'hover:bg-gray-700',
    filterHover: 'hover:text-gray-200',
    clearAllText: 'text-red-500 hover:text-red-700',
    successText: 'text-green-400',
    missedText: 'text-red-400',
    //accentColor: 'blue-400',
    //accentBg: 'bg-blue-600',
    accentText: 'text-white',
    accentColor: 'purple-500',
    accentBg: 'bg-gradient-to-r from-purple-500 to-pink-500',
    accentShadow: 'shadow-[0_0_20px_rgba(168, 85, 247, 0.8)]',
    focusRing: 'focus:ring-blue-800',
    baccentText: 'text-blue-400',
    bfilterHover: 'hover:bg-blue-700 hover:text-blue-300',
    messageBg: 'bg-gray-900',
  };
  
  export const theme = { light, dark };
  